project_id = "qtlhqsqanbxgfbcjigrl"

[functions.analyze-quiz]
verify_jwt = false

[functions.rank-career-paths]
verify_jwt = false

[functions.deep-quiz-analysis]
verify_jwt = false

[functions.generate-therapy-images]
verify_jwt = false
