import React, { useRef } from 'react';
import { useQuiz } from '@/contexts/QuizContext';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Progress } from '@/components/ui/progress';
import { RotateCcw, Download, Copy } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';

export function QuizResults() {
  const { state, resetQuiz } = useQuiz();
  const { toast } = useToast();
  const results = state.results!;
  const resultsRef = useRef<HTMLDivElement>(null);

  const generateComprehensiveText = () => {
    return `
COMPREHENSIVE CAREER ASSESSMENT RESULTS
=====================================

Assessment Overview:
- Confidence Level: ${results.confidence}%
- Completed: ${results.completedAt.toLocaleDateString()}

TOP CAREER PATHS
===============

${results.careerPaths.map((cp, i) => `
${i + 1}. ${cp.title.toUpperCase()} (${cp.score}% MATCH)
${'-'.repeat(50)}

Description:
${cp.description}

Key Traits:
${cp.keyTraits.map(trait => `• ${trait}`).join('\n')}

Typical Roles:
${cp.typicalRoles.map(role => `• ${role}`).join('\n')}

Work Environment:
${cp.workEnvironment}

Strengths in This Path:
${cp.strengths.map(strength => `• ${strength}`).join('\n')}

Potential Challenges:
${cp.challenges.map(challenge => `• ${challenge}`).join('\n')}

`).join('\n')}

COMPREHENSIVE PERSONALITY PROFILE
================================

YOUR STRENGTHS:
${results.personalityInsight.strengths.map(strength => `• ${strength}`).join('\n')}

AREAS FOR GROWTH:
${results.personalityInsight.areasForGrowth.map(area => `• ${area}`).join('\n')}

YOUR WORKING STYLE:
${results.personalityInsight.workingStyle}

WHAT MOTIVATES YOU:
${results.personalityInsight.motivators.map(motivator => `• ${motivator}`).join('\n')}

YOUR NATURAL TENDENCIES:
${results.personalityInsight.naturalTendencies.map(tendency => `• ${tendency}`).join('\n')}

RELATIONSHIP INSIGHTS:
${results.personalityInsight.relationshipStyles.map(style => `• ${style}`).join('\n')}

ENVIRONMENTS TO APPROACH WITH CAUTION:
${results.personalityInsight.avoidanceAreas.map(area => `• ${area}`).join('\n')}

---
Generated by Comprehensive Career Assessment Quiz
Assessment Date: ${results.completedAt.toLocaleDateString()}
    `;
  };

  const handleCopyResults = () => {
    const comprehensiveText = generateComprehensiveText();
    navigator.clipboard.writeText(comprehensiveText);
    toast({
      title: "Results Copied",
      description: "Comprehensive results copied to clipboard!",
    });
  };

  const handleDownloadPDF = async () => {
    if (!resultsRef.current) return;
    
    try {
      toast({
        title: "Generating PDF",
        description: "Please wait while we create your PDF...",
      });

      // Configure html2canvas for better quality
      const canvas = await html2canvas(resultsRef.current, {
        scale: 2,
        useCORS: true,
        allowTaint: true,
        backgroundColor: '#ffffff',
        width: resultsRef.current.scrollWidth,
        height: resultsRef.current.scrollHeight,
      });

      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF('p', 'mm', 'a4');
      
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = pdf.internal.pageSize.getHeight();
      const imgWidth = canvas.width;
      const imgHeight = canvas.height;
      
      // Calculate scaling to fit page
      const ratio = Math.min(pdfWidth / imgWidth, pdfHeight / imgHeight);
      const scaledWidth = imgWidth * ratio;
      const scaledHeight = imgHeight * ratio;
      
      // Center the image
      const x = (pdfWidth - scaledWidth) / 2;
      const y = (pdfHeight - scaledHeight) / 2;
      
      pdf.addImage(imgData, 'PNG', x, y, scaledWidth, scaledHeight);
      pdf.save('career-assessment-results.pdf');
      
      toast({
        title: "PDF Downloaded",
        description: "Your results have been saved as a PDF!",
      });
    } catch (error) {
      toast({
        title: "Error",
        description: "Failed to generate PDF. Please try again.",
        variant: "destructive",
      });
    }
  };

  return (
    <div className="min-h-screen bg-background">
      <div className="container mx-auto px-4 py-8">
        <div ref={resultsRef} className="max-w-4xl mx-auto space-y-8">
          {/* Header */}
          <div className="text-center space-y-4">
            <h1 className="text-4xl font-bold bg-quiz-gradient bg-clip-text text-transparent">
              Your Career Assessment Results
            </h1>
            <p className="text-xl text-muted-foreground">
              Based on comprehensive psychological analysis of your responses
            </p>
            <div className="flex items-center justify-center gap-4">
              <Badge variant="outline" className="text-sm">
                Confidence: {results.confidence}%
              </Badge>
              <Badge variant="outline" className="text-sm">
                Completed: {results.completedAt.toLocaleDateString()}
              </Badge>
            </div>
          </div>

          {/* Career Paths */}
          <div className="space-y-6">
            <h2 className="text-2xl font-semibold text-center">Your Top Career Paths</h2>
            <div className="grid gap-6">
              {results.careerPaths.map((career, index) => (
                <Card key={career.id} className="p-6 bg-quiz-card border-border shadow-quiz">
                  <div className="space-y-4">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-4">
                        <div className="text-3xl font-bold text-primary">
                          #{index + 1}
                        </div>
                        <div>
                          <h3 className="text-xl font-semibold">{career.title}</h3>
                          <div className="flex items-center gap-2 mt-1">
                            <Progress value={career.score} className="w-32 h-2" />
                            <span className="text-sm font-medium text-primary">
                              {career.score}% match
                            </span>
                          </div>
                        </div>
                      </div>
                    </div>

                    <p className="text-muted-foreground">{career.description}</p>

                    <div className="grid md:grid-cols-2 gap-4 text-sm">
                      <div>
                        <h4 className="font-medium mb-2">Key Traits</h4>
                        <div className="flex flex-wrap gap-1">
                          {career.keyTraits.map((trait) => (
                            <Badge key={trait} variant="secondary" className="text-xs">
                              {trait}
                            </Badge>
                          ))}
                        </div>
                      </div>

                      <div>
                        <h4 className="font-medium mb-2">Typical Roles</h4>
                        <div className="flex flex-wrap gap-1">
                          {career.typicalRoles.map((role) => (
                            <Badge key={role} variant="outline" className="text-xs">
                              {role}
                            </Badge>
                          ))}
                        </div>
                      </div>
                    </div>

                    <div className="grid md:grid-cols-2 gap-4 text-sm">
                      <div>
                        <h4 className="font-medium mb-2 text-green-400">Strengths</h4>
                        <ul className="list-disc list-inside space-y-1 text-muted-foreground">
                          {career.strengths.map((strength) => (
                            <li key={strength}>{strength}</li>
                          ))}
                        </ul>
                      </div>

                      <div>
                        <h4 className="font-medium mb-2 text-orange-400">Challenges</h4>
                        <ul className="list-disc list-inside space-y-1 text-muted-foreground">
                          {career.challenges.map((challenge) => (
                            <li key={challenge}>{challenge}</li>
                          ))}
                        </ul>
                      </div>
                    </div>

                    <div>
                      <h4 className="font-medium mb-2">Work Environment</h4>
                      <p className="text-sm text-muted-foreground">{career.workEnvironment}</p>
                    </div>
                  </div>
                </Card>
              ))}
            </div>
          </div>

          {/* Personality Insights */}
          <Card className="p-6 bg-quiz-card border-border shadow-quiz">
            <div className="space-y-6">
              <h2 className="text-2xl font-semibold text-center">Your Personality Profile</h2>

              <div className="grid md:grid-cols-2 gap-6">
                <div>
                  <h3 className="font-semibold mb-3 text-green-400">Your Strengths</h3>
                  <ul className="space-y-2">
                    {results.personalityInsight.strengths.map((strength) => (
                      <li key={strength} className="flex items-start gap-2">
                        <div className="w-2 h-2 rounded-full bg-green-400 mt-2 flex-shrink-0" />
                        <span className="text-sm">{strength}</span>
                      </li>
                    ))}
                  </ul>
                </div>

                <div>
                  <h3 className="font-semibold mb-3 text-orange-400">Areas for Growth</h3>
                  <ul className="space-y-2">
                    {results.personalityInsight.areasForGrowth.map((area) => (
                      <li key={area} className="flex items-start gap-2">
                        <div className="w-2 h-2 rounded-full bg-orange-400 mt-2 flex-shrink-0" />
                        <span className="text-sm">{area}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>

              <div>
                <h3 className="font-semibold mb-3">Your Working Style</h3>
                <p className="text-muted-foreground">{results.personalityInsight.workingStyle}</p>
              </div>

              <div>
                <h3 className="font-semibold mb-3">What Motivates You</h3>
                <div className="flex flex-wrap gap-2">
                  {results.personalityInsight.motivators.map((motivator) => (
                    <Badge key={motivator} variant="secondary">
                      {motivator}
                    </Badge>
                  ))}
                </div>
              </div>

              <div>
                <h3 className="font-semibold mb-3">Your Natural Tendencies</h3>
                <ul className="space-y-1">
                  {results.personalityInsight.naturalTendencies.map((tendency) => (
                    <li key={tendency} className="text-sm text-muted-foreground">
                      • {tendency}
                    </li>
                  ))}
                </ul>
              </div>

              <div>
                <h3 className="font-semibold mb-3">Relationship Insights</h3>
                <ul className="space-y-1">
                  {results.personalityInsight.relationshipStyles.map((style) => (
                    <li key={style} className="text-sm text-muted-foreground">
                      • {style}
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          </Card>

          {/* Actions */}
          <div className="flex flex-wrap justify-center gap-4">
            <Button onClick={handleDownloadPDF} variant="outline" className="flex items-center gap-2">
              <Download className="w-4 h-4" />
              Download PDF
            </Button>
            <Button onClick={handleCopyResults} variant="outline" className="flex items-center gap-2">
              <Copy className="w-4 h-4" />
              Copy Results To Clipboard
            </Button>
            <Button onClick={resetQuiz} variant="default" className="flex items-center gap-2 bg-quiz-gradient">
              <RotateCcw className="w-4 h-4" />
              Take Quiz Again
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
}