import React, { useRef } from 'react';
import { useQuiz } from '@/contexts/QuizContext';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Progress } from '@/components/ui/progress';
import { RotateCcw, Download, Copy } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import { AIAnalysisStatus, AIAnalysisLoading } from './AIAnalysisStatus';
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';

export function QuizResults() {
  const { state, resetQuiz } = useQuiz();
  const { toast } = useToast();
  const results = state.results!;
  const resultsRef = useRef<HTMLDivElement>(null);

  const generateComprehensiveText = () => {
    const text = `
COMPREHENSIVE CAREER ASSESSMENT RESULTS
=====================================

Assessment Overview:
- Confidence Level: ${results.confidence}%
- Completed: ${results.completedAt.toLocaleDateString()}

TOP CAREER PATHS
===============

${results.careerPaths.map((cp, i) => `
${i + 1}. ${cp.title.toUpperCase()} (${cp.score}% MATCH)
${'-'.repeat(50)}

Description:
${cp.description}

Key Traits:
${cp.keyTraits.map(trait => `• ${trait}`).join('\n')}

Typical Roles:
${cp.typicalRoles.map(role => `• ${role}`).join('\n')}

${cp.specificOccupations ? `Specific Occupations:
${cp.specificOccupations.map(occ => `• ${occ}`).join('\n')}` : ''}

Work Environment:
${cp.workEnvironment}

Strengths in This Path:
${cp.strengths.map(strength => `• ${strength}`).join('\n')}

Potential Challenges:
${cp.challenges.map(challenge => `• ${challenge}`).join('\n')}

`).join('\n')}

${results.aiAnalysis?.specificOccupations ? `
SPECIFIC CAREER RECOMMENDATIONS (AI-ENHANCED)
===========================================

${results.aiAnalysis.specificOccupations.map((occ, i) => `
${i + 1}. ${occ.title.toUpperCase()} (${occ.fitScore}% FIT)
${'-'.repeat(40)}
Category: ${occ.category}
Reasoning: ${occ.reasoning}

`).join('\n')}` : ''}

COMPREHENSIVE PERSONALITY PROFILE
================================

YOUR STRENGTHS:
${results.personalityInsight.strengths.map(strength => `• ${strength}`).join('\n')}

AREAS FOR GROWTH:
${results.personalityInsight.areasForGrowth.map(area => `• ${area}`).join('\n')}

YOUR WORKING STYLE:
${results.personalityInsight.workingStyle}

WHAT MOTIVATES YOU:
${results.personalityInsight.motivators.map(motivator => `• ${motivator}`).join('\n')}

YOUR NATURAL TENDENCIES:
${results.personalityInsight.naturalTendencies.map(tendency => `• ${tendency}`).join('\n')}

RELATIONSHIP INSIGHTS:
${results.personalityInsight.relationshipStyles.map(style => `• ${style}`).join('\n')}

ENVIRONMENTS TO APPROACH WITH CAUTION:
${results.personalityInsight.avoidanceAreas.map(area => `• ${area}`).join('\n')}

${results.aiAnalysis?.hiddenBeliefs ? `
HIDDEN BELIEFS & PSYCHOLOGICAL PATTERNS (AI ANALYSIS)
===================================================

SUCCESS BLOCKERS:
${results.aiAnalysis.hiddenBeliefs.successBlockers.map(blocker => `• ${blocker}`).join('\n')}

MONEY BELIEFS:
${results.aiAnalysis.hiddenBeliefs.moneyBeliefs.map(belief => `• ${belief}`).join('\n')}

FEAR PATTERNS:
${results.aiAnalysis.hiddenBeliefs.fearPatterns.map(pattern => `• ${pattern}`).join('\n')}

CORE PSYCHOLOGICAL INSIGHTS:
${results.aiAnalysis.hiddenBeliefs.coreInsights.map(insight => `• ${insight}`).join('\n')}` : ''}

${results.aiAnalysis?.enhancedPersonality ? `

ENHANCED PERSONALITY ANALYSIS (AI-POWERED)
========================================

COGNITIVE STYLE:
${results.aiAnalysis.enhancedPersonality.cognitiveStyle}

MOTIVATIONAL DRIVERS:
${results.aiAnalysis.enhancedPersonality.motivationalDrivers.map(driver => `• ${driver}`).join('\n')}

RELATIONSHIP STYLE:
${results.aiAnalysis.enhancedPersonality.relationshipStyle}

WORK ENVIRONMENT NEEDS:
${results.aiAnalysis.enhancedPersonality.workEnvironmentNeeds}` : ''}

---
Generated by Comprehensive Career Assessment Quiz with AI Enhancement
Assessment Date: ${results.completedAt.toLocaleDateString()}
    `;

    return text;
  };

  const handleCopyResults = () => {
    const comprehensiveText = generateComprehensiveText();
    navigator.clipboard.writeText(comprehensiveText);
    toast({
      title: "Results Copied",
      description: "Comprehensive results copied to clipboard!",
    });
  };

  const handleDownloadPDF = async () => {
    if (!resultsRef.current) return;

    try {
      toast({
        title: "Generating PDF",
        description: "Please wait while we create your PDF...",
      });

      // Configure html2canvas for better quality
      const canvas = await html2canvas(resultsRef.current, {
        scale: 2,
        useCORS: true,
        allowTaint: true,
        backgroundColor: '#181715',
        width: resultsRef.current.scrollWidth,
        height: resultsRef.current.scrollHeight,
      });

      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF('p', 'mm', 'a4');

      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = pdf.internal.pageSize.getHeight();
      const imgWidth = canvas.width;
      const imgHeight = canvas.height;

      // Calculate scaling to fit page
      const ratio = Math.min(pdfWidth / imgWidth, pdfHeight / imgHeight);
      const scaledWidth = imgWidth * ratio;
      const scaledHeight = imgHeight * ratio;

      // Center the image
      const x = (pdfWidth - scaledWidth) / 2;
      const y = (pdfHeight - scaledHeight) / 2;

      pdf.addImage(imgData, 'PNG', x, y, scaledWidth, scaledHeight);
      pdf.save('career-assessment-results.pdf');

      toast({
        title: "PDF Downloaded",
        description: "Your results have been saved as a PDF!",
      });
    } catch (error) {
      toast({
        title: "Error",
        description: "Failed to generate PDF. Please try again.",
        variant: "destructive",
      });
    }
  };

  return (
    <div className="min-h-screen bg-background">
      <div className="container mx-auto px-4 py-8">
        <div ref={resultsRef} className="max-w-4xl mx-auto space-y-8">
          {/* Header */}
          <div className="text-center space-y-4">
            <h1 className="text-4xl font-bold">
              Your Career Assessment Results
            </h1>
            <p className="text-xl text-muted-foreground">
              Based on comprehensive psychological analysis of your responses
            </p>
            <div className="flex items-center justify-center gap-4">
              <Badge variant="outline" className="text-sm">
                Confidence: {results.confidence}%
              </Badge>
              <Badge variant="outline" className="text-sm">
                Completed: {results.completedAt.toLocaleDateString()}
              </Badge>
            </div>
          </div>

          {/* AI Analysis Status */}
          <AIAnalysisStatus
            isLoading={state.isAiAnalysisLoading}
            hasError={!!state.aiAnalysisError}
            errorMessage={state.aiAnalysisError || undefined}
            hasResults={!!results.aiAnalysis}
          />

          {/* Career Paths */}
          <div className="space-y-6">
            <h2 className="text-2xl font-semibold text-center">Your Top Career Paths</h2>
            <div className="grid gap-6">
              {results.careerPaths.map((career, index) => (
                <Card key={career.id} className="p-6 bg-quiz-card border-border shadow-quiz">
                  <div className="space-y-4">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-4">
                        <div className="text-3xl font-bold text-primary">
                          #{index + 1}
                        </div>
                        <div>
                          <h3 className="text-xl font-semibold">{career.title}</h3>
                          <div className="flex items-center gap-2 mt-1">
                            <Progress value={career.score} className="w-32 h-2" />
                            <span className="text-sm font-medium text-primary">
                              {career.score}% match
                            </span>
                          </div>
                        </div>
                      </div>
                    </div>

                    <p className="text-muted-foreground">{career.description}</p>

                    <div className="grid md:grid-cols-2 gap-4 text-sm">
                      <div>
                        <h4 className="font-medium mb-2">Key Traits</h4>
                        <div className="flex flex-wrap gap-1">
                          {career.keyTraits.map((trait) => (
                            <Badge key={trait} variant="secondary" className="text-xs">
                              {trait}
                            </Badge>
                          ))}
                        </div>
                      </div>

                      <div>
                        <h4 className="font-medium mb-2">Typical Roles</h4>
                        <div className="flex flex-wrap gap-1">
                          {career.typicalRoles.map((role) => (
                            <Badge key={role} variant="outline" className="text-xs">
                              {role}
                            </Badge>
                          ))}
                        </div>
                      </div>
                    </div>

                    <div className="grid md:grid-cols-2 gap-4 text-sm">
                      <div>
                        <h4 className="font-medium mb-2 text-accent">Strengths</h4>
                        <ul className="list-disc list-inside space-y-1 text-muted-foreground">
                          {career.strengths.map((strength) => (
                            <li key={strength}>{strength}</li>
                          ))}
                        </ul>
                      </div>

                      <div>
                        <h4 className="font-medium mb-2 text-secondary">Challenges</h4>
                        <ul className="list-disc list-inside space-y-1 text-muted-foreground">
                          {career.challenges.map((challenge) => (
                            <li key={challenge}>{challenge}</li>
                          ))}
                        </ul>
                      </div>
                    </div>

                    <div>
                      <h4 className="font-medium mb-2">Work Environment</h4>
                      <p className="text-sm text-muted-foreground">{career.workEnvironment}</p>
                    </div>
                  </div>
                </Card>
              ))}
            </div>
          </div>

          {/* Personality Insights */}
          <Card className="p-6 bg-quiz-card border-border shadow-quiz">
            <div className="space-y-6">
              <h2 className="text-2xl font-semibold text-center">Your Personality Profile</h2>

              <div className="grid md:grid-cols-2 gap-6">
                <div>
                  <h3 className="font-semibold mb-3 text-accent">Your Strengths</h3>
                  <ul className="space-y-2">
                    {results.personalityInsight.strengths.map((strength) => (
                      <li key={strength} className="flex items-start gap-2">
                        <div className="w-2 h-2 rounded-full bg-accent mt-2 flex-shrink-0" />
                        <span className="text-sm">{strength}</span>
                      </li>
                    ))}
                  </ul>
                </div>

                <div>
                  <h3 className="font-semibold mb-3 text-secondary">Areas for Growth</h3>
                  <ul className="space-y-2">
                    {results.personalityInsight.areasForGrowth.map((area) => (
                      <li key={area} className="flex items-start gap-2">
                        <div className="w-2 h-2 rounded-full bg-secondary mt-2 flex-shrink-0" />
                        <span className="text-sm">{area}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>

              <div>
                <h3 className="font-semibold mb-3">Your Working Style</h3>
                <p className="text-muted-foreground">{results.personalityInsight.workingStyle}</p>
              </div>

              <div>
                <h3 className="font-semibold mb-3">What Motivates You</h3>
                <div className="flex flex-wrap gap-2">
                  {results.personalityInsight.motivators.map((motivator) => (
                    <Badge key={motivator} variant="secondary">
                      {motivator}
                    </Badge>
                  ))}
                </div>
              </div>

              <div>
                <h3 className="font-semibold mb-3">Your Natural Tendencies</h3>
                <ul className="space-y-1">
                  {results.personalityInsight.naturalTendencies.map((tendency) => (
                    <li key={tendency} className="text-sm text-muted-foreground">
                      • {tendency}
                    </li>
                  ))}
                </ul>
              </div>

              <div>
                <h3 className="font-semibold mb-3">Relationship Insights</h3>
                <ul className="space-y-1">
                  {results.personalityInsight.relationshipStyles.map((style) => (
                    <li key={style} className="text-sm text-muted-foreground">
                      • {style}
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          </Card>

          {/* AI Analysis - Specific Occupations */}
          {state.isAiAnalysisLoading ? (
            <Card className="p-6 bg-quiz-card border-border shadow-quiz">
              <div className="space-y-4">
                <h2 className="text-2xl font-semibold text-center">Specific Career Recommendations</h2>
                <AIAnalysisLoading message="Analyzing your responses to generate specific career recommendations..." />
              </div>
            </Card>
          ) : results.aiAnalysis?.specificOccupations && results.aiAnalysis.specificOccupations.length > 0 ? (
            <Card className="p-6 bg-quiz-card border-border shadow-quiz">
              <div className="space-y-4">
                <h2 className="text-2xl font-semibold text-center">Specific Career Recommendations</h2>
                <div className="grid gap-4">
                  {results.aiAnalysis.specificOccupations.map((occupation) => (
                    <div key={occupation.title} className="border border-border rounded-lg p-4">
                      <div className="flex items-center justify-between mb-2">
                        <h3 className="font-semibold">{occupation.title}</h3>
                        <div className="text-sm text-primary font-medium">{occupation.fitScore}% fit</div>
                      </div>
                      <p className="text-sm text-muted-foreground mb-2">Category: {occupation.category}</p>
                      <p className="text-sm">{occupation.reasoning}</p>
                    </div>
                  ))}
                </div>
              </div>
            </Card>
          ) : null}

          {/* Hidden Beliefs & Blockers Analysis */}
          {state.isAiAnalysisLoading ? (
            <Card className="p-6 bg-quiz-card border-border shadow-quiz">
              <div className="space-y-6">
                <h2 className="text-2xl font-semibold text-center">Hidden Beliefs & Psychological Patterns</h2>
                <AIAnalysisLoading message="Analyzing psychological patterns and hidden beliefs..." />
              </div>
            </Card>
          ) : results.aiAnalysis?.hiddenBeliefs ? (
            <Card className="p-6 bg-quiz-card border-border shadow-quiz">
              <div className="space-y-6">
                <h2 className="text-2xl font-semibold text-center">Hidden Beliefs & Psychological Patterns</h2>

                <div className="grid md:grid-cols-2 gap-6">
                  <div>
                    <h3 className="font-semibold mb-3 text-red-600">Success Blockers</h3>
                    <ul className="space-y-2">
                      {results.aiAnalysis.hiddenBeliefs.successBlockers.map((blocker, index) => (
                        <li key={index} className="flex items-start gap-2">
                          <div className="w-2 h-2 rounded-full bg-destructive mt-2 flex-shrink-0" />
                          <span className="text-sm">{blocker}</span>
                        </li>
                      ))}
                    </ul>
                  </div>

                  <div>
                    <h3 className="font-semibold mb-3 text-primary">Money Beliefs</h3>
                    <ul className="space-y-2">
                      {results.aiAnalysis.hiddenBeliefs.moneyBeliefs.map((belief, index) => (
                        <li key={index} className="flex items-start gap-2">
                          <div className="w-2 h-2 rounded-full bg-primary mt-2 flex-shrink-0" />
                          <span className="text-sm">{belief}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>

                <div>
                  <h3 className="font-semibold mb-3 text-secondary">Fear Patterns</h3>
                  <div className="flex flex-wrap gap-2">
                    {results.aiAnalysis.hiddenBeliefs.fearPatterns.map((pattern, index) => (
                      <Badge key={index} variant="secondary">
                        {pattern}
                      </Badge>
                    ))}
                  </div>
                </div>

                <div>
                  <h3 className="font-semibold mb-3 text-accent">Core Insights</h3>
                  <ul className="space-y-3">
                    {results.aiAnalysis.hiddenBeliefs.coreInsights.map((insight, index) => (
                      <li key={index} className="text-sm text-muted-foreground p-3 bg-background/50 rounded border-l-4 border-accent">
                        {insight}
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            </Card>
          ) : null}

          {/* Enhanced Personality Analysis */}
          {state.isAiAnalysisLoading ? (
            <Card className="p-6 bg-quiz-card border-border shadow-quiz">
              <div className="space-y-6">
                <h2 className="text-2xl font-semibold text-center">Enhanced Personality Analysis</h2>
                <AIAnalysisLoading message="Generating enhanced personality insights..." />
              </div>
            </Card>
          ) : results.aiAnalysis?.enhancedPersonality ? (
            <Card className="p-6 bg-quiz-card border-border shadow-quiz">
              <div className="space-y-6">
                <h2 className="text-2xl font-semibold text-center">Enhanced Personality Analysis</h2>

                <div>
                  <h3 className="font-semibold mb-3 text-purple-500">Cognitive Style</h3>
                  <p className="text-sm text-muted-foreground">{results.aiAnalysis.enhancedPersonality.cognitiveStyle}</p>
                </div>

                <div>
                  <h3 className="font-semibold mb-3 text-rose-500">Motivational Drivers</h3>
                  <div className="flex flex-wrap gap-2">
                    {results.aiAnalysis.enhancedPersonality.motivationalDrivers.map((driver, index) => (
                      <Badge key={index} variant="secondary">
                        {driver}
                      </Badge>
                    ))}
                  </div>
                </div>

                <div>
                  <h3 className="font-semibold mb-3 text-cyan-400">Relationship Style</h3>
                  <p className="text-sm text-muted-foreground">{results.aiAnalysis.enhancedPersonality.relationshipStyle}</p>
                </div>

                <div>
                  <h3 className="font-semibold mb-3 text-yellow-300">Work Environment Needs</h3>
                  <p className="text-sm text-muted-foreground">{results.aiAnalysis.enhancedPersonality.workEnvironmentNeeds}</p>
                </div>
              </div>
            </Card>
          ) : null}

          {/* Actions */}
          <div className="flex flex-wrap justify-center gap-4">
            <Button onClick={handleDownloadPDF} variant="outline" className="flex items-center gap-2">
              <Download className="w-4 h-4" />
              Download PDF
            </Button>
            <Button onClick={handleCopyResults} variant="outline" className="flex items-center gap-2">
              <Copy className="w-4 h-4" />
              Copy Results To Clipboard
            </Button>
            <Button onClick={resetQuiz} variant="default" className="flex items-center gap-2 bg-primary hover:bg-primary/90">
              <RotateCcw className="w-4 h-4" />
              Take Quiz Again
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
}
